using System.Security.Cryptography;
using CfiApp.Application.Abstractions;
using Microsoft.Extensions.Options;

namespace CfiApp.Infrastructure.Files;

public sealed class LocalFileStorageOptions
{
    public const string SectionName = "FileStorage";

    /// <summary>Absolute or relative-to-content-root path. Kept outside wwwroot so files are never served directly.</summary>
    public string RootPath { get; set; } = "storage/uploads";
}

/// <summary>
/// Disk-backed implementation of <see cref="IFileStorage"/>.
///
/// Files are named by their own content hash rather than the name they arrived with:
/// that makes the storage key collision-free, means an identical photo uploaded twice
/// reuses the same bytes, and guarantees nothing from an uploaded file name (including a
/// path) ever reaches the filesystem path.
/// </summary>
public sealed class LocalFileStorage(IOptions<LocalFileStorageOptions> options) : IFileStorage
{
    public async Task<StoredFile> SaveAsync(
        Stream content, string suggestedExtension, CancellationToken cancellationToken)
    {
        Directory.CreateDirectory(options.Value.RootPath);

        var tempPath = Path.Combine(options.Value.RootPath, $".tmp-{Guid.NewGuid():N}");

        long byteSize;
        byte[] hash;

        using var sha256 = SHA256.Create();

        await using (var fileStream = new FileStream(tempPath, FileMode.CreateNew, FileAccess.Write))
        await using (var hashingStream = new CryptoStream(fileStream, sha256, CryptoStreamMode.Write))
        {
            await content.CopyToAsync(hashingStream, cancellationToken);
            await hashingStream.FlushFinalBlockAsync(cancellationToken);
            byteSize = fileStream.Length;
        }

        hash = sha256.Hash!;

        var sha256Hex = Convert.ToHexString(hash).ToLowerInvariant();
        var extension = string.IsNullOrWhiteSpace(suggestedExtension) ? "" : suggestedExtension;
        var storageKey = $"{sha256Hex}{extension}";
        var finalPath = Path.Combine(options.Value.RootPath, storageKey);

        if (File.Exists(finalPath))
        {
            // Identical content already stored under this hash - keep the existing bytes.
            File.Delete(tempPath);
        }
        else
        {
            File.Move(tempPath, finalPath);
        }

        return new StoredFile(storageKey, byteSize, sha256Hex);
    }

    public Task<Stream?> OpenReadAsync(string storageKey, CancellationToken cancellationToken)
    {
        // The storage key is always a hash-derived name generated by SaveAsync, never a
        // caller-supplied path, so there is nothing here for a path traversal attempt to
        // reach - but Path.Combine plus this check keeps that true even if that ever changes.
        var path = Path.Combine(options.Value.RootPath, storageKey);
        var fullRoot = Path.GetFullPath(options.Value.RootPath);
        var fullPath = Path.GetFullPath(path);

        if (!fullPath.StartsWith(fullRoot, StringComparison.Ordinal) || !File.Exists(fullPath))
        {
            return Task.FromResult<Stream?>(null);
        }

        Stream stream = new FileStream(fullPath, FileMode.Open, FileAccess.Read, FileShare.Read);
        return Task.FromResult<Stream?>(stream);
    }
}
